name: nicol_rh8d
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - certifi=2024.6.2
  - charset-normalizer=2.0.4
  - cudatoolkit=10.2.89
  - ffmpeg=4.3
  - freetype=2.12.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - idna=3.7
  - intel-openmp=2023.1.0
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libdeflate=1.8
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.4.0
  - libunistring=0.9.10
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - ncurses=6.4
  - nettle=3.7.3
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.0.13
  - pillow=10.3.0
  - pip=24.0
  - pysocks=1.7.1
  - python=3.9.19
  - pytorch=1.12.1
  - pytorch-mutex=1.0
  - readline=8.2
  - sqlite=3.45.3
  - tbb=2021.8.0
  - tk=8.6.14
  - torchaudio=0.12.1
  - torchtext=0.13.1
  - torchvision=0.13.1
  - typing_extensions=4.11.0
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - addict==2.4.0
      - aliyun-python-sdk-core==2.15.1
      - aliyun-python-sdk-kms==2.16.3
      - attributee==0.1.9
      - catkin-pkg==1.0.0
      - cffi==1.16.0
      - chumpy==0.70
      - click==8.1.7
      - colorama==0.4.6
      - colored==2.2.4
      - contourpy==1.2.1
      - crcmod==1.7
      - cryptography==42.0.8
      - cycler==0.12.1
      - cython==3.0.10
      - distro==1.9.0
      - docutils==0.21.2
      - dotty-dict==1.3.1
      - empy==3.3.4
      - filelock==3.14.0
      - fonttools==4.53.0
      - importlib-metadata==7.1.0
      - importlib-resources==6.4.0
      - jmespath==0.10.0
      - json-tricks==3.17.3
      - kiwisolver==1.4.5
      - lap==0.4.0
      - markdown==3.6
      - markdown-it-py==3.0.0
      - matplotlib==3.9.0
      - mdurl==0.1.2
      - mmcls==0.25.0
      - mmcv-full==1.6.2
      - mmdet==2.28.2
      - mmpose==0.29.0
      - mmtrack==0.14.0
      - model-index==0.1.11
      - motmetrics==1.4.0
      - munkres==1.1.4
      - numpy==1.26.4
      - opencv-python==4.10.0.82
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openxlab==0.1.0
      - ordered-set==4.1.0
      - oss2==2.17.0
      - packaging==24.0
      - pandas==1.3.5
      - platformdirs==4.2.2
      - pycocotools==2.0.7
      - pycparser==2.22
      - pycryptodome==3.20.0
      - pygments==2.18.0
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - pytz==2023.4
      - pyyaml==6.0.1
      - requests==2.28.2
      - rich==13.4.2
      - rospkg==1.5.1
      - scipy==1.6.1
      - seaborn==0.13.2
      - setuptools==60.2.0
      - six==1.16.0
      - tabulate==0.9.0
      - terminaltables==3.1.10
      - tomli==2.0.1
      - tqdm==4.65.2
      - tzdata==2024.1
      - urllib3==1.26.18
      - xmltodict==0.13.0
      - xtcocotools==1.14.3
      - yapf==0.40.2
      - zipp==3.19.2
